### ISSUE TITLE
Images not being rendered in generated docs

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#225]
### This is a
- [x] Bug report
- [ ] Feature request

### Description
When I generate the documentation for my project [BrimeNotes/android](https://github.com/BrimeNotes/android.git) everything is working fine, except the images are not being rendered.

Here the link to the project README.md: https://github.com/BrimeNotes/android/blob/master/README.md
Here's the link to the generated documentation: http://yaydoc.herokuapp.com/preview/ujjwalb1996@gmail.com/eff353de-77df-42a8-a6ee-66cf14281dda_preview/

![image](https://user-images.githubusercontent.com/8245662/27923435-f62787a0-629b-11e7-9d48-ee0511f70eb8.png)

**Comment by pri22296** [comment]
@imujjwal96 While investigating this, I realized that, The image does not render because it was never included in the build by sphinx. For sphinx to include static files, they must be placed inside the `_static` directory inside `DOCPATH`. Also for logos, I would recommend using the `LOGO` environment variable. That would give better results in this case.
However,  I found another issue related to the value of `ROOT_DIR` being incorrect when `DOCPATH` is `.` which leads to incorrect index.rst generated.

**Comment by imujjwal96** [comment]
@pri22296  will it be possible if we grab all the image files from the repository and copy it inside the _static directory? and then give relative links for the images

**Comment by pri22296** [comment]
Will the user provide us with a list of paths to images or we'll have to crawl the repository to search for images and copy all of them to _static? The second approach may lead to a large number of images being pushed irrespective of whether they are used or not. Would that be a problem?

**Comment by imujjwal96** [comment]
I don't think that would be possible from the webUI. Maybe we can give a Disclaimer about keeping images in the static directory. If that doesn't happen we will crawl for all the images in the repository.

**Comment by pri22296** [comment]
There are more complications here. Markdown is inherently less powerful than ReST. For ReST we have directives, such as `img` for referencing elements and sphinx resolves them while building. Markdown doesn't have them. For Markdown, there would have to be explicit links to images by the user like `_static/Logo.png`. But then this wouldn't work on github. One way I can think of is to detect and modify links to images while building using regex but then here also, there are some problems. There are too many edge cases here. Let me experiment a bit with `recommonmark`.

**Comment by pri22296** [comment]
@imujjwal96 It seems that sphinx already has this feature. Sphinx will include all images referenced in any document in an `_images` directory and generate appropriate links to it. It doesn't work in your case because It doesn't really understand `/Logo-branding/logo_0.5x.png?raw=true`. Removing `raw=true` does the trick. Apart from this, there were other issues related to markdown to rst conversion such as requiring a empty line before the image link. This happens because Pandoc's GFM reader doesn't exactly mimic Github's markdown. We really can do nothing about it. Although This should be fixed in the future(no information about timeline)  as both Github and Pandoc are moving towards `cmark` which should remove these subtle differences. See https://github.com/jgm/pandoc/issues/3509

Image rendered after making the mentioned changes
https://pri22296.github.io/testYaydoc2/

**Comment by imujjwal96** [comment]
Amazing!!!!

**Comment by pri22296** [comment]
@imujjwal96 Close this then?
