### ISSUE TITLE
Integrating other documentation generators (like javadocs) with yaydoc

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/yaydoc#255]
### This is a
- [ ] Bug report
- [x] Feature request

### Description

There are certain projects, like the Susi AI Project (https://github.com/fossasia/susi_server/), which involve the use of [javadocs](http://www.oracle.com/technetwork/articles/java/index-jsp-135444.html) for generating API documentation in HTML format from Java source code. We should integrate such documentation generators with Yaydoc so that the process of documentation generation from source code can be combined with the exisiting process in which we generate documentation from .rst or markdown files

**Comment by imujjwal96** [comment]
Here's a snippet from https://github.com/fossasia/susi_server/blob/development/.utility/push-docs-to-gh-pages.sh
![image](https://user-images.githubusercontent.com/8245662/28114371-3a5ac3e8-671e-11e7-8f0c-3e9d943dd6e7.png)

This is how the project is currently combining javadocs documentation. 

@pri22296 @sch00lb0y  How can we move forward from here?

**Comment by pri22296** [comment]
From what I understand after taking a look at susi_server repository, javadoc is generated as html, and is then included in the built docs by a bash script. I'm not sure if buidling javadocs from the webUI would be viable. It would require all sorts of tools specific to java which makes sense to be present in travis, but should they also be present in the webUI? This would have been possible with the travis implementation(which we are planning to remove) as then a user could have just run the javadocs command after building the docs.

Here are some of the alternatives from a user's perspective I could think of:
- Javadocs could be hosted else where and linked from the generated documentation(Not ideal)
- use the current javaapi option of yaydoc instead of javadocs. It's not as powerful as javadocs itself but It does generates a pretty decent api doc
- Somehow using travis to deploy javadocs to gh-pages after yaydoc has deployed on each commit.(No idea how that works)

**Comment by imujjwal96** [comment]
Prepare a script and execute it by adding to the Travis configuration file!

**Comment by pri22296** [comment]
@imujjwal96 can you elaborate?

**Comment by imujjwal96** [comment]
We prepare a script that generates javadocs and publish to gh-pages and Add this script to user's travis configuration using webhook

**Comment by pri22296** [comment]
This is the script which susi_server uses for that. https://github.com/fossasia/susi_server/blob/development/gradlew . I am not sure how can we generate this and ensure that it is generic enough to be directly used in any repo. Should we really integrate it with yaydoc or just leave it to the user to do that considering each repo might have some specific needs?

**Comment by imujjwal96** [comment]
@pri22296 where are the javadocs in the ghpages branch?

**Comment by pri22296** [comment]
I wondered about that too. [This](https://github.com/fossasia/susi_server/tree/71b465bca1dca9dbd8c2a38d015e9b93e98512d2) is the last commit where javadocs are present. Not sure if this is an error.

**Comment by imujjwal96** [comment]
![image](https://user-images.githubusercontent.com/8245662/28116091-20df4a18-6725-11e7-92e8-e5d94e854ded.png)

**Comment by imujjwal96** [comment]
@pri22296  Here are the changes that caused the removal of javadoc
https://github.com/fossasia/susi_server/commit/279c0c1788042fc99306c719890fb84943a42e94

**Comment by sch00lb0y** [comment]
btw I having one more doubt how we can link the documentation generated by the Javadoc and documentation generated sphinx together. In susi they copying the documentation generated by the Javadoc and sphinx in the folder. but then the index.html don't have relation with the documentation generated by Javadoc so if the user hit the documentation site they won't be able to see the documentation generated by Javadoc. I think we have to make a custom script for this also to link.

**Comment by imujjwal96** [comment]
The user may manually add a link to javadocs i their README.md

**Comment by sch00lb0y** [comment]
@pri22296 That script is auto generated. we don't have to care about generating that. Java project which having gradle as a build tool will have gradlew in the root dir. for example take a look of open-event-andorid https://github.com/fossasia/open-event-android/tree/development/android

**Comment by pri22296** [comment]
@sch00lb0y Do all java projects have a gradlew script at the root repository?

**Comment by sch00lb0y** [comment]
nope if the java project which having Gradle as a build system it'll have gradlew file

**Comment by pri22296** [comment]
So how do we generalize it for all javaprojects? What other build systems are used and how do we generate javadoc for them?

**Comment by sch00lb0y** [comment]
if they have gradlew in the root dir we'll generate from Javadoc(we have to ask root dir as well because open-event-android having their java files in the android folder) . if it doesn't we'll go with autoapi(current implementation). In order to implement in WEBUI, we need custom environment rather than HEROKU(not sure about this. Have to research whether there is any build pack).

**Comment by imujjwal96** [comment]
There has been some update with this.

As Susi_server is also generating API docs with Swagger, we will also have to accomodate that

**Comment by pri22296** [comment]
> In order to implement in WEBUI, we need custom environment rather than HEROKU(not sure about this. Have to research whether there is any build pack).

@sch00lb0y any update?

**Comment by sch00lb0y** [comment]
@pri22296 it can be done on Heroku. https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku but we can't sure that it'll work for sure. because when I'm trying to compile susi_server I got build error on my local machine. I'll ping with the susi_server developer and check what is the reason. I'll update the status here.

**Comment by sch00lb0y** [comment]
we can generate doc without any build system like Gradle. just by running `javadoc -sourcepath ./src -d ./docs`. javadoc will be installed automatically as soon as we install JDK.
