### ISSUE TITLE
[Question]  choosing base language 

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/yaydoc#62]
I have wrote a simple AST parser for improper conversion of md to rst #57 . but when i'm trying to parse big. i'm getting `RecursionError: maximum recursion depth exceeded in comparison`  recursion limit exceed error. so i don't think we can proceed further with python. for time being should i add recursion limit like this `sys.setrecursionlimit(35000)` or should i port the code into any other language.
@niranjan94 @pri22296 @imujjwal96  @yukiisbored @jig08 @mariobehling  please give me your input.
Thanks

**Comment by yukiisbored** [comment]
I think we don't need to convert existing documents since Sphinx can technically support any type of documents, we just need a plugin that's able to parse it (like reCommonMark). I highly suggest avoid converting them without a human checking and validating it due to common problems that can happen with it. 

We should just use the documents we have at first and we this is successfully deployed, we can start rewriting documents to rST which is the native document format supported by Sphinx/docutils.

**Comment by sch00lb0y** [comment]
@pri22296 @imujjwal96 please give your view fast. because we have to start the web ui #85

**Comment by mariobehling** [comment]
@yukiisbored makes sense as far as I can see. Therefore closing this.
